apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nginx-cluster
  region: us-east-1
  version: "1.28"

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-04e63c7b4a46622cc }
      us-east-1b: { id: subnet-026dc88e5f2f02b11 }
      us-east-1c: { id: subnet-0015221fa02d9809d }
    public:
      us-east-1a: { id: subnet-048c65606b3839e24 }
      us-east-1b: { id: subnet-002c5314939d6f494 }
      us-east-1c: { id: subnet-00fa9b9080507bd69 }

managedNodeGroups:
  - name: nginx-cluster
    minSize: 2
    maxSize: 3
    desiredCapacity: 1
    instanceType: t3.medium
    labels: { role: worker }
    ssh:
      publicKeyName: nginxapp
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
