apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nginx-cluster
  region: us-east-1
  version: "1.28"

vpc:
  subnets:
    private:
      us-east-1b: { id: subnet-010793736f4190af6 }
      us-east-1a: { id: subnet-090b31052dd640a0c }
      us-east-1c: { id: subnet-07d562bee2db55c52 }
    public:
      us-east-1a: { id: subnet-07f4c4e3f20a812eb }
      us-east-1b: { id: subnet-08d0396982c223bb8 }
      us-east-1c: { id: subnet-07d51d9e16ef34eb5 }

managedNodeGroups:
  - name: nginx-cluster
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    instanceType: t3.medium
    labels: { role: worker }
    ssh:
      publicKeyName: nginxapp
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
