apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nginx-cluster
  region: us-east-1
  version: "1.28"

vpc:
  subnets:
    private:
      us-east-1b: { id: subnet-id }
      us-east-1a: { id: subnet-id }
      us-east-1c: { id: subnet-id }
    public:
      us-east-1a: { id: subnet-id }
      us-east-1b: { id: subnet-id }
      us-east-1c: { id: subnet-id }

managedNodeGroups:
  - name: nginx-cluster
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    instanceType: t3.medium
    labels: { role: worker }
    ssh:
      publicKeyName: nginxapp
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
