apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nginx-cluster
  region: us-east-1
  version: "1.28"

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0b152eb5dac016dc8 }
      us-east-1b: { id: subnet-09d26b8b41b456fbe }
      us-east-1c: { id: subnet-0d891e5e50cbb950e }
    public:
      us-east-1a: { id: subnet-0c29daa0ef0790e66 }
      us-east-1b: { id: subnet-0e953c68b5d2978bb }
      us-east-1c: { id: subnet-08e2be8723ab47905 }

managedNodeGroups:
  - name: nginx-cluster
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    instanceType: t3.medium
    labels: { role: worker }
    ssh:
      publicKeyName: nginxapp
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
